<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Petersen">

<title>Final Project Template</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="final_project_template_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_project_template_files/libs/quarto-html/quarto.js"></script>
<script src="final_project_template_files/libs/quarto-html/popper.min.js"></script>
<script src="final_project_template_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_project_template_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_project_template_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_project_template_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_project_template_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_project_template_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_project_template_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project Template</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Petersen </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">vroom</span>(<span class="st">"Cancer_Data.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">38</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>This study employs logistic regression to model the relationship between the diagnosis of a tumor as either malignant, or benign, and some selected features including the mean radius and texture of the tumor. After performing a LASSO variable selection, the logistic regression model yields coefficients for radius_mean (Estimate = 0.65634, p-value &lt; 0.001), texture_mean (Estimate = 0.32593, p-value &lt; 0.001), and concave points_mean (Estimate = 1.01166, p-value &lt; 0.001). Tuning the cutoff threshold lead to an estimated (90%) sentitivity and (97%) specificity in our best model.</p>
</section>
<section id="problem-and-motivation" class="level1">
<h1>1 Problem and Motivation</h1>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">1.1 Data Description</h2>
<p>Millions of people each year are diagnosed with cancer; most people know someone who has it. One very important part of cancer is whether or not it is dangerous. In other words, if the cancer is benign (harmless) or malignant (harmful). The data from this study was found on Kaggle and the authors’ goal was to gather data on a number of predictors that can help in predicting whether or not a cancer is benign or malignant. To start out with, we removed some variables that we did not want to test. The variables that we kept were the ones that measured the mean. We got rid of everything that measured the “worst” of a predictor and the standard error of the predictor. We did this not only to help with interpretability (it is a lot easier to understand how the mean area of a tumor is associated with the response rather than the standard error of its area), but also because we were only curious about how those certain variables were related to a tumor being benign or malignant. There also was not clear documentation on what “worst” meant in the context of this data set, so that is another reason we removed those variables. After doing some further variable selection using the LASSO Shrinkage Method, the variables that we will be using in this project are radius_mean, texture_mean, and concave points_mean. Radius_mean is the average radius in millimeters taken from the center to the edges of the tumor along multiple different lines. Texture_mean is an average normalized measurement of how textured a tumor is. Finally, concave points_mean is an average normalized measure of the concavity of the concave points in a given portion of the tumor. The texture_mean and concave points_mean covariates do not have units given in the description of the data set. After some research into these sorts of tests with tumors, we discovered that the units for these variables are usually decided “in-house,” meaning that it is often a ratio of the tumor’s texture against itself. That is to say the unit is almost arbitrary and will differ from test to test and facility to facility. Thus, for the purpose of this project, we will furthermore just refer to the units for texture_mean and concave points_mean as “texture score” and “concave score.”</p>
</section>
<section id="questions-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="questions-of-interest">1.2 Questions of Interest</h2>
<p>Does the mean radius of a tumor have a significant relationship with its status as benign or malignant? Is there a relationship between the texture of a tumor and its status as benign or malignant?</p>
</section>
<section id="regression-methods" class="level2">
<h2 class="anchored" data-anchor-id="regression-methods">1.3 Regression Methods</h2>
<p>To answer the first question about prediction, we will mostly be relying on logistic regression and the techniques we learned during Module 7. We will also be using some predictive analytic techniques to see how well we are able to predict the malignancy of tumors. To answer the second question, we will also be using logistic regression, specifically the output of our Generalized Logistic Regression model. We will be looking at the p-value of radius_mean to determine the answer to this question.</p>
</section>
</section>
<section id="analyses-results-and-interpretation" class="level1">
<h1>2 Analyses, Results, and Interpretation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diagnosis =</span> <span class="fu">as.factor</span>(diagnosis)) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, <span class="st">`</span><span class="at">concave points_mean</span><span class="st">`</span>, symmetry_mean, fractal_dimension_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>create_boxplot <span class="ot">&lt;-</span> <span class="cf">function</span>(predictor) {</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> predictor, <span class="at">x =</span> diagnosis)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  plot</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>radius_mean)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>texture_mean)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>perimeter_mean)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>area_mean)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>smoothness_mean)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>compactness_mean)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>concavity_mean)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">concave points_mean</span><span class="st">`</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plot9 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>symmetry_mean)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plot10 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(df<span class="sc">$</span>fractal_dimension_mean)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2 <span class="sc">+</span> plot3 <span class="sc">+</span> plot4 <span class="sc">+</span> plot5 <span class="sc">+</span> plot6 <span class="sc">+</span> plot7 <span class="sc">+</span> plot8 <span class="sc">+</span> plot9 <span class="sc">+</span> plot10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="no-multicollinearity-using-vifs" class="level2">
<h2 class="anchored" data-anchor-id="no-multicollinearity-using-vifs">No multicollinearity (using VIFs)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df.lm <span class="ot">=</span> <span class="fu">glm</span>(diagnosis <span class="sc">~</span> ., <span class="at">data =</span> df, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">'logit'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(<span class="fu">select</span>(df, <span class="sc">-</span>diagnosis)), <span class="at">type =</span> <span class="st">'upper'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(df.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           radius_mean           texture_mean         perimeter_mean 
            899.370948               1.806626             698.864791 
             area_mean        smoothness_mean       compactness_mean 
            129.663816               4.375401              15.284985 
        concavity_mean  `concave points_mean`          symmetry_mean 
              5.262546               5.858563               1.839473 
fractal_dimension_mean 
              9.789119 </code></pre>
</div>
</div>
</section>
<section id="lasso-shrinkage-method" class="level2">
<h2 class="anchored" data-anchor-id="lasso-shrinkage-method">LASSO Shrinkage Method</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(df, <span class="sc">-</span>diagnosis))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df_y <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">select</span>(df, diagnosis) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">mutate</span>(<span class="at">diagnosis =</span> <span class="fu">ifelse</span>(diagnosis <span class="sc">==</span> <span class="st">'M'</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>df_LASSO_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> df_x, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> df_y, </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">type.measure =</span> <span class="st">"auc"</span>, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">alpha =</span> <span class="dv">1</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(df_LASSO_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(df_LASSO_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>11 x 1 sparse Matrix of class "dgCMatrix"
                                s1
(Intercept)            -10.2296854
radius_mean              0.3040700
texture_mean             0.1363117
perimeter_mean           .        
area_mean                .        
smoothness_mean          .        
compactness_mean         .        
concavity_mean           .        
concave points_mean     55.2038122
symmetry_mean            .        
fractal_dimension_mean   .        </code></pre>
</div>
</div>
</section>
<section id="fit-a-new-model" class="level2">
<h2 class="anchored" data-anchor-id="fit-a-new-model">Fit a new model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(diagnosis <span class="sc">~</span> radius_mean <span class="sc">+</span> texture_mean <span class="sc">+</span> <span class="st">`</span><span class="at">concave points_mean</span><span class="st">`</span>, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> df,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diagnosis ~ radius_mean + texture_mean + `concave points_mean`, 
    family = binomial(link = "logit"), data = df)

Coefficients:
                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)           -21.16413    2.51041  -8.431  &lt; 2e-16 ***
radius_mean             0.65634    0.12533   5.237 1.63e-07 ***
texture_mean            0.32593    0.05529   5.895 3.75e-09 ***
`concave points_mean` 101.16618   13.02078   7.770 7.87e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 750.51  on 567  degrees of freedom
Residual deviance: 164.38  on 564  degrees of freedom
AIC: 172.38

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p><span class="math inline">\(\log(\frac{\pi_i}{1-\pi_i})=-21.164 + 0.656\times \text{radius mean}_i + 0.326\times \text{texture mean}_i + 101.166\times \text{texture_mean}_i\)</span></p>
<p>Where <span class="math inline">\(\pi_i = P(diagnosis_i = 1 | \text{radius mean}_i, \text{texture mean}_i, \text{texture_mean}_i)\)</span> and <span class="math inline">\(diagnosis_i \stackrel{iid}{\sim} Bernoulli(\pi_i)\)</span></p>
</section>
<section id="no-multicollinearity-using-vifs-1" class="level2">
<h2 class="anchored" data-anchor-id="no-multicollinearity-using-vifs-1">No multicollinearity (using VIFs)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># real R^2</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df_lm <span class="ot">&lt;-</span> <span class="fu">glm</span>(diagnosis <span class="sc">~</span> radius_mean <span class="sc">+</span> texture_mean <span class="sc">+</span> <span class="st">`</span><span class="at">concave points_mean</span><span class="st">`</span>, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> <span class="fu">mutate</span>(df, <span class="at">diagnosis =</span> <span class="fu">ifelse</span>(diagnosis <span class="sc">==</span> <span class="st">'M'</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(df_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          radius_mean          texture_mean `concave points_mean` 
             3.160992              1.124151              3.091396 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">vif</span>(df_lm))  <span class="co"># less than 10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.160992</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">vif</span>(df_lm))  <span class="co"># less than 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.458846</code></pre>
</div>
</div>
<p>Our Variance Inflation Factors (VIFs) have a mean less than 5 and a maximum less than 10. We may assume there is no extreme multicollinearity in our model.</p>
</section>
<section id="the-xs-vs-log-odds-are-linear-monotone-in-probability" class="level2">
<h2 class="anchored" data-anchor-id="the-xs-vs-log-odds-are-linear-monotone-in-probability">The x’s vs log odds are linear (monotone in probability)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_numeric <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">diagnosis =</span> <span class="fu">ifelse</span>(diagnosis <span class="sc">==</span> <span class="st">'B'</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter.smooth</span>(<span class="at">x =</span> df_numeric<span class="sc">$</span>radius_mean, <span class="at">y =</span> df_numeric<span class="sc">$</span>diagnosis <span class="sc">+</span> .<span class="dv">0001</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter.smooth</span>(<span class="at">x =</span> df<span class="sc">$</span>texture_mean, <span class="at">y =</span> df_numeric<span class="sc">$</span>diagnosis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter.smooth</span>(<span class="at">x =</span> df<span class="sc">$</span><span class="st">`</span><span class="at">concave points_mean</span><span class="st">`</span>, <span class="at">y =</span> df_numeric<span class="sc">$</span>diagnosis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>None of our plots show extreme non-linearity. We may assume the x’s vs log odds are linear.</p>
</section>
<section id="the-observations-are-independent" class="level2">
<h2 class="anchored" data-anchor-id="the-observations-are-independent">The observations are independent</h2>
<p>Each of the observations in our dataset has a unique ID number and is assumed to have been randomly collected. We will assume that our observations are independent.</p>
</section>
<section id="the-response-variable-is-bernoulli" class="level2">
<h2 class="anchored" data-anchor-id="the-response-variable-is-bernoulli">The response variable is Bernoulli</h2>
<p>Our response variable is modeled by a Bernoulli distribution, with the only possible outcomes being Malignant (True) and Benign (False).</p>
</section>
<section id="no-counfounding-variables" class="level2">
<h2 class="anchored" data-anchor-id="no-counfounding-variables">No counfounding variables</h2>
<p>We will assume that we have accounted for all variables of significance in our model.</p>
</section>
<section id="influential-observations" class="level2">
<h2 class="anchored" data-anchor-id="influential-observations">Influential observations:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_logistic, <span class="at">which =</span> <span class="dv">5</span>)  <span class="co"># residuals vs leverage</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>None of our observations appear unduly influential based on our Cook’s plot.</p>
<p>All of our assumptions are met. We may proceed to statistical inference.</p>
</section>
<section id="findings-and-interpretations" class="level2">
<h2 class="anchored" data-anchor-id="findings-and-interpretations">Findings and Interpretations</h2>
<p>Now that we have met all the assumptions for the data, we can interpret the relationships between tumor malignancy and key tumor measurements.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diagnosis ~ radius_mean + texture_mean + `concave points_mean`, 
    family = binomial(link = "logit"), data = df)

Coefficients:
                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)           -21.16413    2.51041  -8.431  &lt; 2e-16 ***
radius_mean             0.65634    0.12533   5.237 1.63e-07 ***
texture_mean            0.32593    0.05529   5.895 3.75e-09 ***
`concave points_mean` 101.16618   13.02078   7.770 7.87e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 750.51  on 567  degrees of freedom
Residual deviance: 164.38  on 564  degrees of freedom
AIC: 172.38

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">*</span> (<span class="fu">exp</span>(.<span class="dv">65634</span>) <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 92.77239</code></pre>
</div>
</div>
<p>Holding all else constant, for every unit increase in the mean radius (mm) of a tumor, the probability of the tumor being malignant increases by 92.77%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">*</span> (<span class="fu">exp</span>(.<span class="dv">32593</span>) <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38.53184</code></pre>
</div>
</div>
<p>Holding all else constant, for every unit increase in the mean texture score of a tumor, the probability of the tumor being malignant increases by 38.53%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Because the range for mean texture score is so low, we will divide the coefficient by 1000 and interpret it based on unit increases of .001</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">*</span> (<span class="fu">exp</span>(.<span class="dv">10116618</span>) <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.64605</code></pre>
</div>
</div>
<p>Holding all else constant, for every .001 unit increase in the mean concave points score of a tumor, the probability of the tumor being malignant increases by 10.65%</p>
</section>
</section>
<section id="conclusions" class="level1">
<h1>3 Conclusions</h1>
<p>Looking at the summary from our generalized linear model output, we can see that the p-values for all three of our predictors are much less than <span class="math inline">\(\alpha\)</span> = 0.05. Since this is the case, we reject the null hypothesis. There is sufficient evidence to conclude that radius_mean, texture_mean, and concave points_mean all have a significant relationship with the malignancy of a tumor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the predicted probabilities for all 757 patients:</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>df_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(df_logistic,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create a sequence from 0 to 1 to represent all possible cut-off values (c) </span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># that we could choose:</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>possible_cutoffs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># transform heart$chd from a factor with levels "yes" and "no" to a factor with </span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># levels 1 and 0:</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>df_binary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>diagnosis <span class="sc">==</span> <span class="st">"M"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># create an empty vector where we will store the percent misclassified for each</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># possible cut-off value we created:</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>percent_misclass <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">length</span>(possible_cutoffs))</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="co"># for each possible cut-off value, (1) grab the cut-off value, (2) for all 757</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="co"># patients, store a 1 in "classify" if their predicted probability is larger </span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co"># than the cut-off value, and (3) compute the average percent misclassified </span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co"># across the 757 patients when using that cut-off by averaging the number of </span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co"># times "classify" (0 or 1 based on how that cut-off classified a person) is </span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co"># not the same as heart_binary (the truth):</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(possible_cutoffs)){</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  classify <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_preds <span class="sc">&gt;</span> possible_cutoffs[i], <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  percent_misclass[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(classify <span class="sc">!=</span> df_binary)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>  percent_misclass</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>percent_misclass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 0.62676056 0.28345070 0.20598592 0.19190141 0.16901408 0.14788732
  [7] 0.13732394 0.12676056 0.12852113 0.12323944 0.11619718 0.10739437
 [13] 0.10035211 0.09507042 0.09507042 0.09330986 0.09330986 0.08450704
 [19] 0.08450704 0.08450704 0.08274648 0.08274648 0.08802817 0.08802817
 [25] 0.08626761 0.08450704 0.08450704 0.08274648 0.08098592 0.07570423
 [31] 0.07218310 0.07218310 0.07218310 0.06866197 0.07042254 0.07042254
 [37] 0.06866197 0.06866197 0.07042254 0.07042254 0.06866197 0.06866197
 [43] 0.06866197 0.06690141 0.06514085 0.06338028 0.06161972 0.05985915
 [49] 0.06161972 0.05985915 0.05809859 0.05809859 0.05809859 0.05809859
 [55] 0.05633803 0.05457746 0.05457746 0.05457746 0.05985915 0.06338028
 [61] 0.06338028 0.06161972 0.06338028 0.06161972 0.05985915 0.06161972
 [67] 0.06338028 0.06514085 0.06514085 0.06514085 0.06514085 0.06514085
 [73] 0.06514085 0.07042254 0.07218310 0.07218310 0.07218310 0.07218310
 [79] 0.07218310 0.07394366 0.07570423 0.07394366 0.07570423 0.07746479
 [85] 0.07746479 0.07746479 0.08098592 0.08274648 0.08274648 0.08450704
 [91] 0.08626761 0.08978873 0.09154930 0.09859155 0.10035211 0.10387324
 [97] 0.11267606 0.11971831 0.13204225 0.15492958 0.37323944</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># percent_misclass holds the average misclassification rates for each cut-off</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>misclass_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(percent_misclass, possible_cutoffs))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># put this information in a dataframe so we can plot it with ggplot:</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> misclass_df) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> possible_cutoffs, <span class="at">y =</span> percent_misclass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the misclassification rate against the cut-off value:</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> misclass_df) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> possible_cutoffs, <span class="at">y =</span> percent_misclass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_template_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># choose the "best" cut-off that minimizes the percent misclassified:</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>cutoff_best <span class="ot">&lt;-</span> possible_cutoffs[<span class="fu">which.min</span>(percent_misclass)]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a confusion matrix with the truth and the predicted classification: </span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> df_preds <span class="sc">&gt;</span> cutoff_best</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>conf_mat <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="st">"Truth"</span> <span class="ot">=</span> df<span class="sc">$</span>diagnosis,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Predicted"</span> <span class="ot">=</span> preds)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>conf_mat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Predicted
Truth FALSE TRUE
    B   346   10
    M    21  191</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note that we can also add column and row sums, which is useful for </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># calculations:</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(conf_mat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Predicted
Truth FALSE TRUE Sum
  B     346   10 356
  M      21  191 212
  Sum   367  201 568</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> <span class="dv">191</span><span class="sc">/</span><span class="dv">212</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>sensitivity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9009434</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> <span class="dv">346</span><span class="sc">/</span><span class="dv">356</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>specificity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9719101</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">&lt;-</span> <span class="dv">191</span><span class="sc">/</span><span class="dv">201</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>precision</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9502488</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>neg_pred_val <span class="ot">&lt;-</span> <span class="dv">346</span><span class="sc">/</span><span class="dv">367</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>neg_pred_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9427793</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> (<span class="dv">346</span> <span class="sc">+</span> <span class="dv">191</span>) <span class="sc">/</span> <span class="dv">568</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9454225</code></pre>
</div>
</div>
<p>Based on our Confusion Matrix, we see that our model had 10 false positives and 21 false negatives. The sensitivity of our model was 0.90. The specificity was 0.97. The precision (aka Positive Predictive Value) was 0.95. The Negative Predictive Value was 0.94. Finally, the overall Accuracy of the test was 0.95.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>deviance <span class="ot">&lt;-</span> <span class="fl">750.51</span> <span class="sc">-</span> <span class="fl">164.38</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 586.13</code></pre>
</div>
</div>
<p>The Deviance of our model is 586.13.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pseudo_r2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="fl">164.38</span> <span class="sc">/</span> <span class="fl">750.51</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pseudo_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7809756</code></pre>
</div>
</div>
<p>Our psuedo <span class="math inline">\(R^2\)</span> value is 0.78. This means that about 78% of the total variability seen in the log odds can be explained by radius_mean, texture_mean, and concave points_mean.</p>
</section>
<section id="contributions" class="level1">
<h1>4 Contributions</h1>
<p>Ty Hawkes took the lead in finding and cleaning our dataset. He also consistently reviewed code chunks and was dedicated to debugging any issues. Ty wrote the interpretations and generally helped the group out when we were stuck.</p>
<p>Talmage Hilton wrote most of our conclusions and observed results. He was focused on the goals of the project and kept us on track. He also made the confusion matrix and ROC curve to attest to the accuracy of our model.</p>
<p>Chris Gordon checked the assumptions for our model and helped with debugging. He also wrote our fitted model and helped find solutions to problems at each step of the project.</p>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">APPENDIX</h2>
<p>If there are any analyses, such as exploratory plots/summaries or work you did to determine appropriate transformations, or any relevant material that does not belong in one of the sections above, these can go in the Appendix. If you don’t have any material like this, you can remove this section.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>